# For more details on how to create your config file 
# https://makgyver.github.io/fluke/configuration.html
data:
  dataset:
    name: heart_disease
    path: D:/dataset
  distribution:
    name: datasetxia
  sampling_perc: 1
  client_split: 0.2
  keep_test: true
  server_test: true
  server_split: 0 # not used in this case
  uniform_test: false
exp:
  device: cpu
  seed: 42
# save:
#   path: ./models
#   save_every: 5
#   global_only: false
eval:
  task: classification
  eval_every: 1
  pre_fit: false
  post_fit: true
  locals: false
  server: true
logger:
  name: Log
protocol:
  eligible_perc: 0.25
  n_clients: 4
  n_rounds: 40