hyperparameters:
  client:
    batch_size: 64
    local_epochs: 5
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.001
      momentum: 0.5
      # weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  server:
    weighted: true
    bandwidth: 1.0
  model: CNN_Mnist
name: fluke.algorithms.kafe.Kafe
